avoided_ai_cliches = """Avoid common AI cliches like the following :
In the ever-evolving landscape of AI…
Harnessing the power of AI to revolutionize…
At the intersection of technology and innovation…
Disrupting the status quo with cutting-edge AI…
Unlocking unprecedented insights with machine learning…
Driving transformation across industries…
Empowering businesses through intelligent automation…
AI is no longer science fiction — it’s business reality…
Pioneering the future with next-gen AI solutions…
Redefining what’s possible with artificial intelligence…
Give me a response in plain text. Do not use any of the following characters: *, _, ~, `, #, >, -, +, |, for any markdown formatting. 
Just clean, simple text with no bullet points, no bold, no italics, no special symbols.
Output must be a single plain text paragraph (or multiple paragraphs if needed), with no extra whitespace at the beginning or end
"""